### ISSUE TITLE
Login na tela de administração

### ISSUE THREAD

**Issue by mfreitas-hyva** [igormenin/phpsgf#1]
Olá @igormenin! Tudo bem?
Primeiramente, parabéns pela aplicação.
Estou com dificuldade para fazer login na aplicação. 
Na verdade, o que preciso é um usuário e senha válidos, de administrador, para que eu possa iniciar alguns testes.
Você se importaria em fornecer?
Obrigado

Abraços

Marcos Freitas

**Comment by mfreitas-hyva** [comment]
Consegui acessar alterando o fonte do programa!
Abraço

**Comment by Davidson-01** [comment]
estou tentando nesse momento acessar com um usuario valido tambem!! poderia me informar como conseguiu ?

**Comment by Davidson-01** [comment]
> Consegui acessar alterando o fonte do programa! Abraço

estou tentando nesse momento acessar com um usuario valido tambem!! poderia me informar como conseguiu ?
